config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: {registrations: 'registrations', sessions: 'users/sessions'}

  root 'tests#index'

  resources :feedbacks, only: %i[new create] do
    member do
      get :new
      post :create
    end
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, shallow: true, only: :index
    resources :feedbacks, only: %i[index destroy]
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :answer, presence: true
  validate :max_answer_count, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def max_answer_count
    errors.add(:question, "fail") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests
  default_scope { order(category: :asc) }
  validates :category, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  has_many :gists
  belongs_to :test

  validates :question, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :test_passages
  has_many :users, through: :test_passages
  has_many :questions
  belongs_to :category
  belongs_to :user, class_name: 'User', foreign_key: :user_id

  scope :by_level, -> (level) { where(level: level) }
  scope :simple, -> { by_level(0..1) }
  scope :medium, -> { by_level(2..4) }
  scope :complicated, -> { by_level (5..FLOAT::INFINITY) }
  scope :with_category, -> (category_name) { joins(:category).where(categories: { title: category_name }) }

  validates :level, numericality: { only_integer: true, greater_than: 0 }
  validates :title, presence: true, uniqueness: { scope: :level }

  def self.name_tests(category_name)
    with_category(category_name).order(id: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  PASS_VALUE = 85

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def success?
    success_value >= PASS_VALUE
  end

  def success_value
    correct_questions.to_f / test.questions.count.to_f * 100
  end

  def question_num
    test.questions.order(id: :asc).find_index(current_question) + 1
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    correct_user_answers_count = correct_answers.where(id: answer_ids).count
    (correct_answers_count == correct_user_answers_count) && correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :made_tests, class_name: 'Test', foreign_key: :user_id
  has_many :gists
  has_many :feedbacks

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, format: { with: VALID_EMAIL}, uniqueness: { case_sensetive: true }

  def tests_by_level(level)
    tests.by_level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end
end

app/models/user_test_relation.rb
class UserTestRelation < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :set_locale

  def default_url_options
    I18n.locale == I18n.default_locale ? super : {lang: I18n.locale}
  end

  private

  def after_sign_in_path_for(resource)
    if current_user.admin?
      admin_tests_path
    else
      super
    end
  end

  def set_locale
    I18n.locale = I18n.locale_available?(params[:lang]) ? params[:lang] : I18n.default_locale
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test, only: %i[start]

 def index
    @tests = Test.all
  end

  def start
    #byebug
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALERT_TYPES = {
    alert: "danger",
    notice: "info"
  }.freeze

  def flash_messages
    flash.map do |type, message|
      class_type = "flash #{ALERT_TYPES[type.to_sym]}"
      content_tag :div, message, class: class_type, role: 'alert'
    end.join("\n").html_safe
  end

  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to repo, "https://github.com/#{author}/#{repo}", target: '_blank'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper

def question_header
  if @question.persisted?
    "Edit #{@test.title} Question"
  else
    "Create New #{@test.title} Question"
  end
end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def progress_result
    if @tests_passages.test.questions.count > 0
      (@tests_passages.question_num - 1) * 100 / @tests_passages.test.questions.count
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_header
    if @test.persisted?
      t('edit_test', title: @test.title)
    else
      t('create_new_test')
    end
  end
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to t('.testguru'), root_path, class: 'navbar-brand' %> | <%= link_to t('.testguru_admin_panel'), admin_tests_path, class: 'navbar-brand' %> |
    <%= link_to 'Gists', admin_gists_path, class: 'nav-item nav-link' %> |

  <span class="navbar-text">
  <p class="nav user"><b><%= t('.welcome', name: current_user.first_name) %> [<%= link_to t('.log_out'), destroy_user_session_path, method: :delete %>]</b></p>
    </span>
</nav>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <div>
      <h2><%= t('.header', count: resource.errors.count) %></h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "flash #{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<p><%= current_year %> t(.author) <%= github_url("Timur Pavlov", "TestGuru") %> - Passing tests. <%= link_to t('.project'), 'http://thinknetica.com', target: '_blank' %></p>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to t('.project'), root_path, class: 'navbar-brand' %>
  <% if user_signed_in? && current_user.admin?%>
    <%= link_to t('.testguru_admin_panel'), admin_tests_path, class: 'navbar-brand' %>
  <% end %>

  <span class="navbar-text">
    <% if user_signed_in? %>
      <p class="nav user"><b><%= t('.welcome', name: current_user.first_name) %> [<%= link_to t('.log_out'), destroy_user_session_path, method: :delete %>]</b></p>
    <% else  %>
      <p class="nav menu">[<%= link_to t('.log_in'), new_user_session_path %>][<%= link_to t('.sign_up'), new_user_registration_path %>]</p>
    <% end %>
  </span>
</nav>