config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: {registrations: 'registrations', sessions: 'users/sessions'}

  root 'tests#index'

  resources :feedbacks, only: %i[new create] do
    member do
      get :new
      post :create
    end
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, shallow: true, only: :index
    resources :feedbacks, only: %i[index destroy]
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  has_many :gists
  belongs_to :test

  validates :question, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  PASS_VALUE = 85

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def success?
    success_value >= PASS_VALUE
  end

  def success_value
    correct_questions.to_f / test.questions.count.to_f * 100
  end

  def question_num
    test.questions.order(id: :asc).find_index(current_question) + 1
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    correct_user_answers_count = correct_answers.where(id: answer_ids).count
    (correct_answers_count == correct_user_answers_count) && correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

end

app/controllers/test_passages_controller.rb
require "#{Rails.root}/lib/clients/octo_kit_client"

class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_tests_passage, only: %i[show update result gist]

  def show
  end

  def result
  end

  def update
    @tests_passages.accept!(params[:answer_ids])

    if @tests_passages.completed?
      TestsMailer.completed_test(@tests_passages).deliver_now
      redirect_to result_test_passage_path(@tests_passages)
    else
      render :show
    end
  end

  def gist
    result = GistQuestionService.new(@tests_passages.current_question)
    answer = result.call
    flash_options = if result.success?
                      create_gist!(answer.html_url)
                      { notice: t('.success', gist_url: answer[:html_url]) }
                    else
                      { alert: t('.failure') }
                    end
    redirect_to @tests_passages, flash_options
  end

  private

  def set_tests_passage
    @tests_passages = TestPassage.find(params[:id])
  end

  def create_gist!(gist_url)
    current_user.gists.create(question: @tests_passages.current_question, url: gist_url)
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def progress_result
    if @tests_passages.test.questions.count > 0
      (@tests_passages.question_num - 1) * 100 / @tests_passages.test.questions.count
    end
  end
end

app/views/test_passages/result.html.erb
<h1><%= t('.test_completed', test: @tests_passages.test.title) %> </h1>

<% if @tests_passages.success? %>

  <h2><%= t('.passed') %></h2>

  <p>
    <font color="green"><%= t('.result', result: @tests_passages.success_value) %></font>
  </p>

<% else %>

  <h2><%= t('.failed') %></h2>

  <p>
    <font color="red"><%= t('.result', result: @tests_passages.success_value) %></font>
  </p>

<% end %>

<%= link_to t('.back'), tests_path %>

app/views/test_passages/show.html.erb
<h1><%= @tests_passages.test.title %></h1>
<progress value=0 max=100 id="progress" data-progress-percent=<%= progress_result %>></progress>
<i>
  <p>
    <%= t('.question') %> №<%= @tests_passages.question_num %>/<%= @tests_passages.test.questions.count %>
  </p>
</i>

<b>
  <%= @tests_passages.current_question.question %>
</b>

<%= form_with url: test_passage_path(@tests_passages), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @tests_passages.current_question.answers, :id, :answer, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to 'Gist Question', gist_test_passage_path(@tests_passages), method: :post %></p>
  <p><%= form.submit t('.next') %></p>

<% end %>